### ISSUE TITLE
Webkit: features.json

### ISSUE THREAD

**Issue by azu** [mayuki/PlatformStatusTracker#2]
Webkit has provided `features.json` files that are similar to data of https://www.chromestatus.com/features

> [[webkit-dev] Request for feedback: Status page for WebKit](https://lists.webkit.org/pipermail/webkit-dev/2015-March/027351.html "[webkit-dev] Request for feedback: Status page for WebKit")
> My current plan is to have 2 files, named "features.json", with the
information about our features. The files would be in
Source/JavaScriptCore/features.json and Source/WebCore/features.json.

Related:

- [Bug 143207 – Start the features.json files](https://bugs.webkit.org/show_bug.cgi?id=143207 "Bug 143207 – Start the features.json files")

I think it's very interesting if PlatformStatusTracker track these file.
It may be not ready...

**Comment by mayuki** [comment]
Now, PlatformStatusTracker watches WebKit feature.json and reflects to pages.
http://platformstatustracker.azurewebsites.net/Changes/2015-04-09

**Comment by azu** [comment]
Wow! Great work! :clap: 
Thanks.

**Comment by Constellation** [comment]
Great!
