### ISSUE TITLE
Firefox Platform Status

### ISSUE THREAD

**Issue by azu** [mayuki/PlatformStatusTracker#3]
Finally, Firefox start to provide platform status page.

- https://platform-status.mozilla.org/
- https://github.com/mozilla/platatus/

JSON endpoint is here : https://platform-status.mozilla.org/status.json (https://github.com/mozilla/platatus/blob/gh-pages/status.json )
Meaning of the property is here: https://github.com/mozilla/platatus/blob/master/CONTRIBUTING.md

(I think that Firefox Platform Status is under development.)

**Comment by mayuki** [comment]
Thanks. added tracking to Firefox Platform Status.

http://platformstatustracker.azurewebsites.net/Changes/2015-11-25
http://platformstatustracker.azurewebsites.net/Changes/2015-12-07

**Comment by azu** [comment]
@mayuki Thanks! :+1:
